/* This file was generated by SableCC (http://www.sablecc.org/). */

package gcompiler.analysis;

import gcompiler.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTNum(TNum node);
    void caseTId(TId node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTBlank(TBlank node);
    void caseTType(TType node);
    void caseTSemi(TSemi node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
