/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.gcompiler.node;

import java.util.*;
import br.com.ufs.gcompiler.analysis.*;

@SuppressWarnings("nls")
public final class AArgs extends PArgs
{
    private final LinkedList<PArgList> _argList_ = new LinkedList<PArgList>();

    public AArgs()
    {
        // Constructor
    }

    public AArgs(
        @SuppressWarnings("hiding") List<?> _argList_)
    {
        // Constructor
        setArgList(_argList_);

    }

    @Override
    public Object clone()
    {
        return new AArgs(
            cloneList(this._argList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgs(this);
    }

    public LinkedList<PArgList> getArgList()
    {
        return this._argList_;
    }

    public void setArgList(List<?> list)
    {
        for(PArgList e : this._argList_)
        {
            e.parent(null);
        }
        this._argList_.clear();

        for(Object obj_e : list)
        {
            PArgList e = (PArgList) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._argList_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._argList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._argList_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PArgList> i = this._argList_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PArgList) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
