/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.gcompiler.node;

import br.com.ufs.gcompiler.analysis.*;

@SuppressWarnings("nls")
public final class ADivisionMulop extends PMulop
{
    private TDivision _division_;

    public ADivisionMulop()
    {
        // Constructor
    }

    public ADivisionMulop(
        @SuppressWarnings("hiding") TDivision _division_)
    {
        // Constructor
        setDivision(_division_);

    }

    @Override
    public Object clone()
    {
        return new ADivisionMulop(
            cloneNode(this._division_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivisionMulop(this);
    }

    public TDivision getDivision()
    {
        return this._division_;
    }

    public void setDivision(TDivision node)
    {
        if(this._division_ != null)
        {
            this._division_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._division_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._division_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._division_ == child)
        {
            this._division_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._division_ == oldChild)
        {
            setDivision((TDivision) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
