/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.gcompiler.node;

import br.com.ufs.gcompiler.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyStmtList extends PStmtList
{

    public AEmptyStmtList()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AEmptyStmtList();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyStmtList(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
