/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.gcompiler.node;

import br.com.ufs.gcompiler.analysis.*;

@SuppressWarnings("nls")
public final class AExpressionStmtStmt extends PStmt
{
    private PExpressionStmt _expressionStmt_;

    public AExpressionStmtStmt()
    {
        // Constructor
    }

    public AExpressionStmtStmt(
        @SuppressWarnings("hiding") PExpressionStmt _expressionStmt_)
    {
        // Constructor
        setExpressionStmt(_expressionStmt_);

    }

    @Override
    public Object clone()
    {
        return new AExpressionStmtStmt(
            cloneNode(this._expressionStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressionStmtStmt(this);
    }

    public PExpressionStmt getExpressionStmt()
    {
        return this._expressionStmt_;
    }

    public void setExpressionStmt(PExpressionStmt node)
    {
        if(this._expressionStmt_ != null)
        {
            this._expressionStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressionStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionStmt_ == child)
        {
            this._expressionStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressionStmt_ == oldChild)
        {
            setExpressionStmt((PExpressionStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
