/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.gcompiler.node;

import br.com.ufs.gcompiler.analysis.*;

@SuppressWarnings("nls")
public final class AFuncReturnTypeSpec extends PFuncReturnTypeSpec
{
    private PTypeSpec _typeSpec_;

    public AFuncReturnTypeSpec()
    {
        // Constructor
    }

    public AFuncReturnTypeSpec(
        @SuppressWarnings("hiding") PTypeSpec _typeSpec_)
    {
        // Constructor
        setTypeSpec(_typeSpec_);

    }

    @Override
    public Object clone()
    {
        return new AFuncReturnTypeSpec(
            cloneNode(this._typeSpec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncReturnTypeSpec(this);
    }

    public PTypeSpec getTypeSpec()
    {
        return this._typeSpec_;
    }

    public void setTypeSpec(PTypeSpec node)
    {
        if(this._typeSpec_ != null)
        {
            this._typeSpec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeSpec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typeSpec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typeSpec_ == child)
        {
            this._typeSpec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typeSpec_ == oldChild)
        {
            setTypeSpec((PTypeSpec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
