/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.gcompiler.node;

import br.com.ufs.gcompiler.analysis.*;

@SuppressWarnings("nls")
public final class AGreaterThanRelop extends PRelop
{
    private TGreaterThan _greaterThan_;

    public AGreaterThanRelop()
    {
        // Constructor
    }

    public AGreaterThanRelop(
        @SuppressWarnings("hiding") TGreaterThan _greaterThan_)
    {
        // Constructor
        setGreaterThan(_greaterThan_);

    }

    @Override
    public Object clone()
    {
        return new AGreaterThanRelop(
            cloneNode(this._greaterThan_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreaterThanRelop(this);
    }

    public TGreaterThan getGreaterThan()
    {
        return this._greaterThan_;
    }

    public void setGreaterThan(TGreaterThan node)
    {
        if(this._greaterThan_ != null)
        {
            this._greaterThan_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greaterThan_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._greaterThan_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._greaterThan_ == child)
        {
            this._greaterThan_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._greaterThan_ == oldChild)
        {
            setGreaterThan((TGreaterThan) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
