/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.gcompiler.node;

import br.com.ufs.gcompiler.analysis.*;

@SuppressWarnings("nls")
public final class AIterationStmtOtherStmt extends POtherStmt
{
    private PIterationStmt _iterationStmt_;

    public AIterationStmtOtherStmt()
    {
        // Constructor
    }

    public AIterationStmtOtherStmt(
        @SuppressWarnings("hiding") PIterationStmt _iterationStmt_)
    {
        // Constructor
        setIterationStmt(_iterationStmt_);

    }

    @Override
    public Object clone()
    {
        return new AIterationStmtOtherStmt(
            cloneNode(this._iterationStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIterationStmtOtherStmt(this);
    }

    public PIterationStmt getIterationStmt()
    {
        return this._iterationStmt_;
    }

    public void setIterationStmt(PIterationStmt node)
    {
        if(this._iterationStmt_ != null)
        {
            this._iterationStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._iterationStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._iterationStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._iterationStmt_ == child)
        {
            this._iterationStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._iterationStmt_ == oldChild)
        {
            setIterationStmt((PIterationStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
