/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.gcompiler.node;

import br.com.ufs.gcompiler.analysis.*;

@SuppressWarnings("nls")
public final class ALessThanOrEqRelop extends PRelop
{
    private TLessThanOrEq _lessThanOrEq_;

    public ALessThanOrEqRelop()
    {
        // Constructor
    }

    public ALessThanOrEqRelop(
        @SuppressWarnings("hiding") TLessThanOrEq _lessThanOrEq_)
    {
        // Constructor
        setLessThanOrEq(_lessThanOrEq_);

    }

    @Override
    public Object clone()
    {
        return new ALessThanOrEqRelop(
            cloneNode(this._lessThanOrEq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALessThanOrEqRelop(this);
    }

    public TLessThanOrEq getLessThanOrEq()
    {
        return this._lessThanOrEq_;
    }

    public void setLessThanOrEq(TLessThanOrEq node)
    {
        if(this._lessThanOrEq_ != null)
        {
            this._lessThanOrEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lessThanOrEq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lessThanOrEq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lessThanOrEq_ == child)
        {
            this._lessThanOrEq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lessThanOrEq_ == oldChild)
        {
            setLessThanOrEq((TLessThanOrEq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
