/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.gcompiler.node;

import br.com.ufs.gcompiler.analysis.*;

@SuppressWarnings("nls")
public final class ALocalDecl extends PLocalDecl
{
    private PLocalDecl _localDecl_;
    private PVarDecl _varDecl_;

    public ALocalDecl()
    {
        // Constructor
    }

    public ALocalDecl(
        @SuppressWarnings("hiding") PLocalDecl _localDecl_,
        @SuppressWarnings("hiding") PVarDecl _varDecl_)
    {
        // Constructor
        setLocalDecl(_localDecl_);

        setVarDecl(_varDecl_);

    }

    @Override
    public Object clone()
    {
        return new ALocalDecl(
            cloneNode(this._localDecl_),
            cloneNode(this._varDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALocalDecl(this);
    }

    public PLocalDecl getLocalDecl()
    {
        return this._localDecl_;
    }

    public void setLocalDecl(PLocalDecl node)
    {
        if(this._localDecl_ != null)
        {
            this._localDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._localDecl_ = node;
    }

    public PVarDecl getVarDecl()
    {
        return this._varDecl_;
    }

    public void setVarDecl(PVarDecl node)
    {
        if(this._varDecl_ != null)
        {
            this._varDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._localDecl_)
            + toString(this._varDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._localDecl_ == child)
        {
            this._localDecl_ = null;
            return;
        }

        if(this._varDecl_ == child)
        {
            this._varDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._localDecl_ == oldChild)
        {
            setLocalDecl((PLocalDecl) newChild);
            return;
        }

        if(this._varDecl_ == oldChild)
        {
            setVarDecl((PVarDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
