/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.gcompiler.node;

import java.util.*;
import br.com.ufs.gcompiler.analysis.*;

@SuppressWarnings("nls")
public final class AParamParams extends PParams
{
    private final LinkedList<PParamList> _paramList_ = new LinkedList<PParamList>();

    public AParamParams()
    {
        // Constructor
    }

    public AParamParams(
        @SuppressWarnings("hiding") List<?> _paramList_)
    {
        // Constructor
        setParamList(_paramList_);

    }

    @Override
    public Object clone()
    {
        return new AParamParams(
            cloneList(this._paramList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParamParams(this);
    }

    public LinkedList<PParamList> getParamList()
    {
        return this._paramList_;
    }

    public void setParamList(List<?> list)
    {
        for(PParamList e : this._paramList_)
        {
            e.parent(null);
        }
        this._paramList_.clear();

        for(Object obj_e : list)
        {
            PParamList e = (PParamList) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._paramList_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paramList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paramList_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PParamList> i = this._paramList_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PParamList) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
