/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.gcompiler.node;

import br.com.ufs.gcompiler.analysis.*;

@SuppressWarnings("nls")
public final class AVoidTypeSpec extends PTypeSpec
{
    private TVoid _void_;

    public AVoidTypeSpec()
    {
        // Constructor
    }

    public AVoidTypeSpec(
        @SuppressWarnings("hiding") TVoid _void_)
    {
        // Constructor
        setVoid(_void_);

    }

    @Override
    public Object clone()
    {
        return new AVoidTypeSpec(
            cloneNode(this._void_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVoidTypeSpec(this);
    }

    public TVoid getVoid()
    {
        return this._void_;
    }

    public void setVoid(TVoid node)
    {
        if(this._void_ != null)
        {
            this._void_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._void_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._void_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._void_ == child)
        {
            this._void_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._void_ == oldChild)
        {
            setVoid((TVoid) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
