/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.gcompiler.parser;

import br.com.ufs.gcompiler.lexer.*;
import br.com.ufs.gcompiler.node.*;
import br.com.ufs.gcompiler.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    @SuppressWarnings({"unchecked","unused"})
    private void push(int numstate, ArrayList<Object> listNode) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgram node1 = (PProgram) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AProgram */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list);
            }
            break;
            case 1: /* reduce ADeclList */
            {
                ArrayList<Object> list = new1();
                push(goTo(1), list);
            }
            break;
            case 2: /* reduce AVarDeclDecl */
            {
                ArrayList<Object> list = new2();
                push(goTo(2), list);
            }
            break;
            case 3: /* reduce AFuncDeclDecl */
            {
                ArrayList<Object> list = new3();
                push(goTo(2), list);
            }
            break;
            case 4: /* reduce ASimpleVarDecl */
            {
                ArrayList<Object> list = new4();
                push(goTo(3), list);
            }
            break;
            case 5: /* reduce AArrayVarDecl */
            {
                ArrayList<Object> list = new5();
                push(goTo(3), list);
            }
            break;
            case 6: /* reduce A1FuncDecl */
            {
                ArrayList<Object> list = new6();
                push(goTo(4), list);
            }
            break;
            case 7: /* reduce AVoid1FuncDecl */
            {
                ArrayList<Object> list = new7();
                push(goTo(4), list);
            }
            break;
            case 8: /* reduce ALocalDecl */
            {
                ArrayList<Object> list = new8();
                push(goTo(5), list);
            }
            break;
            case 9: /* reduce AEmptyLocalDecl */
            {
                ArrayList<Object> list = new9();
                push(goTo(5), list);
            }
            break;
            case 10: /* reduce AIntTypeSpec */
            {
                ArrayList<Object> list = new10();
                push(goTo(6), list);
            }
            break;
            case 11: /* reduce AStringTypeSpec */
            {
                ArrayList<Object> list = new11();
                push(goTo(6), list);
            }
            break;
            case 12: /* reduce AParamParams */
            {
                ArrayList<Object> list = new12();
                push(goTo(7), list);
            }
            break;
            case 13: /* reduce ANoneParams */
            {
                ArrayList<Object> list = new13();
                push(goTo(7), list);
            }
            break;
            case 14: /* reduce ASequenceParamList */
            {
                ArrayList<Object> list = new14();
                push(goTo(8), list);
            }
            break;
            case 15: /* reduce ASingleParamList */
            {
                ArrayList<Object> list = new15();
                push(goTo(8), list);
            }
            break;
            case 16: /* reduce ASimpleParam */
            {
                ArrayList<Object> list = new16();
                push(goTo(9), list);
            }
            break;
            case 17: /* reduce AArrayParam */
            {
                ArrayList<Object> list = new17();
                push(goTo(9), list);
            }
            break;
            case 18: /* reduce ACompoundStmt */
            {
                ArrayList<Object> list = new18();
                push(goTo(10), list);
            }
            break;
            case 19: /* reduce AStmtList */
            {
                ArrayList<Object> list = new19();
                push(goTo(11), list);
            }
            break;
            case 20: /* reduce AEmptyStmtList */
            {
                ArrayList<Object> list = new20();
                push(goTo(11), list);
            }
            break;
            case 21: /* reduce AMatchedStmtStmt */
            {
                ArrayList<Object> list = new21();
                push(goTo(12), list);
            }
            break;
            case 22: /* reduce AUnmatchedStmtStmt */
            {
                ArrayList<Object> list = new22();
                push(goTo(12), list);
            }
            break;
            case 23: /* reduce AMatchedIfMatchedStmt */
            {
                ArrayList<Object> list = new23();
                push(goTo(13), list);
            }
            break;
            case 24: /* reduce AOtherStmtMatchedStmt */
            {
                ArrayList<Object> list = new24();
                push(goTo(13), list);
            }
            break;
            case 25: /* reduce AUnmatchedIfUnmatchedStmt */
            {
                ArrayList<Object> list = new25();
                push(goTo(14), list);
            }
            break;
            case 26: /* reduce AUnmatchedIfElseUnmatchedStmt */
            {
                ArrayList<Object> list = new26();
                push(goTo(14), list);
            }
            break;
            case 27: /* reduce AExpressionStmtOtherStmt */
            {
                ArrayList<Object> list = new27();
                push(goTo(15), list);
            }
            break;
            case 28: /* reduce ACompoundStmtOtherStmt */
            {
                ArrayList<Object> list = new28();
                push(goTo(15), list);
            }
            break;
            case 29: /* reduce AIterationStmtOtherStmt */
            {
                ArrayList<Object> list = new29();
                push(goTo(15), list);
            }
            break;
            case 30: /* reduce AReturnStmtOtherStmt */
            {
                ArrayList<Object> list = new30();
                push(goTo(15), list);
            }
            break;
            case 31: /* reduce AExpressionStmt */
            {
                ArrayList<Object> list = new31();
                push(goTo(16), list);
            }
            break;
            case 32: /* reduce AEmptyExpressionStmt */
            {
                ArrayList<Object> list = new32();
                push(goTo(16), list);
            }
            break;
            case 33: /* reduce AIterationStmt */
            {
                ArrayList<Object> list = new33();
                push(goTo(17), list);
            }
            break;
            case 34: /* reduce AVoidReturnStmt */
            {
                ArrayList<Object> list = new34();
                push(goTo(18), list);
            }
            break;
            case 35: /* reduce AExpressionReturnStmt */
            {
                ArrayList<Object> list = new35();
                push(goTo(18), list);
            }
            break;
            case 36: /* reduce ASimpleVar */
            {
                ArrayList<Object> list = new36();
                push(goTo(19), list);
            }
            break;
            case 37: /* reduce AArrayVar */
            {
                ArrayList<Object> list = new37();
                push(goTo(19), list);
            }
            break;
            case 38: /* reduce AAssignExpressionExpression */
            {
                ArrayList<Object> list = new38();
                push(goTo(20), list);
            }
            break;
            case 39: /* reduce ASimpleExpressionExpression */
            {
                ArrayList<Object> list = new39();
                push(goTo(20), list);
            }
            break;
            case 40: /* reduce ARelopExpressionSimpleExpression */
            {
                ArrayList<Object> list = new40();
                push(goTo(21), list);
            }
            break;
            case 41: /* reduce AAdditiveExpressionSimpleExpression */
            {
                ArrayList<Object> list = new41();
                push(goTo(21), list);
            }
            break;
            case 42: /* reduce ALessThanOrEqRelop */
            {
                ArrayList<Object> list = new42();
                push(goTo(22), list);
            }
            break;
            case 43: /* reduce ALessThanRelop */
            {
                ArrayList<Object> list = new43();
                push(goTo(22), list);
            }
            break;
            case 44: /* reduce AGreaterThanRelop */
            {
                ArrayList<Object> list = new44();
                push(goTo(22), list);
            }
            break;
            case 45: /* reduce AGreaterThanOrEqRelop */
            {
                ArrayList<Object> list = new45();
                push(goTo(22), list);
            }
            break;
            case 46: /* reduce AEqualsRelop */
            {
                ArrayList<Object> list = new46();
                push(goTo(22), list);
            }
            break;
            case 47: /* reduce ANotEqualsRelop */
            {
                ArrayList<Object> list = new47();
                push(goTo(22), list);
            }
            break;
            case 48: /* reduce AAdditiveExpressionAdditiveExpression */
            {
                ArrayList<Object> list = new48();
                push(goTo(23), list);
            }
            break;
            case 49: /* reduce ATermAdditiveExpression */
            {
                ArrayList<Object> list = new49();
                push(goTo(23), list);
            }
            break;
            case 50: /* reduce APlusAddop */
            {
                ArrayList<Object> list = new50();
                push(goTo(24), list);
            }
            break;
            case 51: /* reduce AMinusAddop */
            {
                ArrayList<Object> list = new51();
                push(goTo(24), list);
            }
            break;
            case 52: /* reduce ATermTerm */
            {
                ArrayList<Object> list = new52();
                push(goTo(25), list);
            }
            break;
            case 53: /* reduce AFactorTerm */
            {
                ArrayList<Object> list = new53();
                push(goTo(25), list);
            }
            break;
            case 54: /* reduce AMultiplicationMulop */
            {
                ArrayList<Object> list = new54();
                push(goTo(26), list);
            }
            break;
            case 55: /* reduce ADivisionMulop */
            {
                ArrayList<Object> list = new55();
                push(goTo(26), list);
            }
            break;
            case 56: /* reduce AFactorFactor */
            {
                ArrayList<Object> list = new56();
                push(goTo(27), list);
            }
            break;
            case 57: /* reduce AVarFactor */
            {
                ArrayList<Object> list = new57();
                push(goTo(27), list);
            }
            break;
            case 58: /* reduce ANumFactor */
            {
                ArrayList<Object> list = new58();
                push(goTo(27), list);
            }
            break;
            case 59: /* reduce AStringFactor */
            {
                ArrayList<Object> list = new59();
                push(goTo(27), list);
            }
            break;
            case 60: /* reduce ACallFactor */
            {
                ArrayList<Object> list = new60();
                push(goTo(27), list);
            }
            break;
            case 61: /* reduce ACall */
            {
                ArrayList<Object> list = new61();
                push(goTo(28), list);
            }
            break;
            case 62: /* reduce ASequenceArgList */
            {
                ArrayList<Object> list = new62();
                push(goTo(29), list);
            }
            break;
            case 63: /* reduce ASingleArgList */
            {
                ArrayList<Object> list = new63();
                push(goTo(29), list);
            }
            break;
            case 64: /* reduce AEmptyArgList */
            {
                ArrayList<Object> list = new64();
                push(goTo(29), list);
            }
            break;
            case 65: /* reduce ATerminal$Decl */
            {
                ArrayList<Object> list = new65();
                push(goTo(30), list);
            }
            break;
            case 66: /* reduce ANonTerminal$Decl */
            {
                ArrayList<Object> list = new66();
                push(goTo(30), list);
            }
            break;
            case 67: /* reduce ATerminal$ParamList */
            {
                ArrayList<Object> list = new67();
                push(goTo(31), list);
            }
            break;
            case 68: /* reduce ANonTerminal$ParamList */
            {
                ArrayList<Object> list = new68();
                push(goTo(31), list);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AProgram */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        PDeclList pdecllistNode2;
        pdecllistNode2 = (PDeclList)nodeArrayList1.get(0);

        pprogramNode1 = new AProgram(pdecllistNode2);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce ADeclList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDeclList pdecllistNode1;
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pdecllistNode1 = new ADeclList(listNode3);
        }
	nodeList.add(pdecllistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce AVarDeclDecl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecl pdeclNode1;
        {
            // Block
        PVarDecl pvardeclNode2;
        pvardeclNode2 = (PVarDecl)nodeArrayList1.get(0);

        pdeclNode1 = new AVarDeclDecl(pvardeclNode2);
        }
	nodeList.add(pdeclNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce AFuncDeclDecl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecl pdeclNode1;
        {
            // Block
        PFuncDecl pfuncdeclNode2;
        pfuncdeclNode2 = (PFuncDecl)nodeArrayList1.get(0);

        pdeclNode1 = new AFuncDeclDecl(pfuncdeclNode2);
        }
	nodeList.add(pdeclNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce ASimpleVarDecl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PVarDecl pvardeclNode1;
        {
            // Block
        PTypeSpec ptypespecNode2;
        TId tidNode3;
        TSemi tsemiNode4;
        ptypespecNode2 = (PTypeSpec)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);
        tsemiNode4 = (TSemi)nodeArrayList3.get(0);

        pvardeclNode1 = new ASimpleVarDecl(ptypespecNode2, tidNode3, tsemiNode4);
        }
	nodeList.add(pvardeclNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce AArrayVarDecl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PVarDecl pvardeclNode1;
        {
            // Block
        PTypeSpec ptypespecNode2;
        TId tidNode3;
        TLeftBracket tleftbracketNode4;
        TNum tnumNode5;
        TRightBracket trightbracketNode6;
        TSemi tsemiNode7;
        ptypespecNode2 = (PTypeSpec)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);
        tleftbracketNode4 = (TLeftBracket)nodeArrayList3.get(0);
        tnumNode5 = (TNum)nodeArrayList4.get(0);
        trightbracketNode6 = (TRightBracket)nodeArrayList5.get(0);
        tsemiNode7 = (TSemi)nodeArrayList6.get(0);

        pvardeclNode1 = new AArrayVarDecl(ptypespecNode2, tidNode3, tleftbracketNode4, tnumNode5, trightbracketNode6, tsemiNode7);
        }
	nodeList.add(pvardeclNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce A1FuncDecl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFuncDecl pfuncdeclNode1;
        {
            // Block
        PFuncReturnTypeSpec pfuncreturntypespecNode2;
        TId tidNode4;
        TLeftParenthesis tleftparenthesisNode5;
        PParams pparamsNode6;
        TRightParenthesis trightparenthesisNode7;
        PCompoundStmt pcompoundstmtNode8;
        {
            // Block
        PTypeSpec ptypespecNode3;
        ptypespecNode3 = (PTypeSpec)nodeArrayList1.get(0);

        pfuncreturntypespecNode2 = new AFuncReturnTypeSpec(ptypespecNode3);
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tleftparenthesisNode5 = (TLeftParenthesis)nodeArrayList3.get(0);
        pparamsNode6 = (PParams)nodeArrayList4.get(0);
        trightparenthesisNode7 = (TRightParenthesis)nodeArrayList5.get(0);
        pcompoundstmtNode8 = (PCompoundStmt)nodeArrayList6.get(0);

        pfuncdeclNode1 = new AFuncDecl(pfuncreturntypespecNode2, tidNode4, tleftparenthesisNode5, pparamsNode6, trightparenthesisNode7, pcompoundstmtNode8);
        }
	nodeList.add(pfuncdeclNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce AVoid1FuncDecl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFuncDecl pfuncdeclNode1;
        {
            // Block
        PFuncReturnTypeSpec pfuncreturntypespecNode2;
        TId tidNode4;
        TLeftParenthesis tleftparenthesisNode5;
        PParams pparamsNode6;
        TRightParenthesis trightparenthesisNode7;
        PCompoundStmt pcompoundstmtNode8;
        {
            // Block
        TVoid tvoidNode3;
        tvoidNode3 = (TVoid)nodeArrayList1.get(0);

        pfuncreturntypespecNode2 = new AVoidFuncReturnTypeSpec(tvoidNode3);
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tleftparenthesisNode5 = (TLeftParenthesis)nodeArrayList3.get(0);
        pparamsNode6 = (PParams)nodeArrayList4.get(0);
        trightparenthesisNode7 = (TRightParenthesis)nodeArrayList5.get(0);
        pcompoundstmtNode8 = (PCompoundStmt)nodeArrayList6.get(0);

        pfuncdeclNode1 = new AFuncDecl(pfuncreturntypespecNode2, tidNode4, tleftparenthesisNode5, pparamsNode6, trightparenthesisNode7, pcompoundstmtNode8);
        }
	nodeList.add(pfuncdeclNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce ALocalDecl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLocalDecl plocaldeclNode1;
        {
            // Block
        PLocalDecl plocaldeclNode2;
        PVarDecl pvardeclNode3;
        plocaldeclNode2 = (PLocalDecl)nodeArrayList1.get(0);
        pvardeclNode3 = (PVarDecl)nodeArrayList2.get(0);

        plocaldeclNode1 = new ALocalDecl(plocaldeclNode2, pvardeclNode3);
        }
	nodeList.add(plocaldeclNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce AEmptyLocalDecl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PLocalDecl plocaldeclNode1;
        {
            // Block

        plocaldeclNode1 = new AEmptyLocalDecl();
        }
	nodeList.add(plocaldeclNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce AIntTypeSpec */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTypeSpec ptypespecNode1;
        {
            // Block
        TInt tintNode2;
        tintNode2 = (TInt)nodeArrayList1.get(0);

        ptypespecNode1 = new AIntTypeSpec(tintNode2);
        }
	nodeList.add(ptypespecNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce AStringTypeSpec */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTypeSpec ptypespecNode1;
        {
            // Block
        TString tstringNode2;
        tstringNode2 = (TString)nodeArrayList1.get(0);

        ptypespecNode1 = new AStringTypeSpec(tstringNode2);
        }
	nodeList.add(ptypespecNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce AParamParams */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParams pparamsNode1;
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pparamsNode1 = new AParamParams(listNode3);
        }
	nodeList.add(pparamsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce ANoneParams */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParams pparamsNode1;
        {
            // Block
        TVoid tvoidNode2;
        tvoidNode2 = (TVoid)nodeArrayList1.get(0);

        pparamsNode1 = new ANoneParams(tvoidNode2);
        }
	nodeList.add(pparamsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce ASequenceParamList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParamList pparamlistNode1;
        {
            // Block
        PParamList pparamlistNode2;
        TComma tcommaNode3;
        PParam pparamNode4;
        pparamlistNode2 = (PParamList)nodeArrayList1.get(0);
        tcommaNode3 = (TComma)nodeArrayList2.get(0);
        pparamNode4 = (PParam)nodeArrayList3.get(0);

        pparamlistNode1 = new ASequenceParamList(pparamlistNode2, tcommaNode3, pparamNode4);
        }
	nodeList.add(pparamlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new15() /* reduce ASingleParamList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParamList pparamlistNode1;
        {
            // Block
        PParam pparamNode2;
        pparamNode2 = (PParam)nodeArrayList1.get(0);

        pparamlistNode1 = new ASingleParamList(pparamNode2);
        }
	nodeList.add(pparamlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new16() /* reduce ASimpleParam */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParam pparamNode1;
        {
            // Block
        PTypeSpec ptypespecNode2;
        TId tidNode3;
        ptypespecNode2 = (PTypeSpec)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pparamNode1 = new ASimpleParam(ptypespecNode2, tidNode3);
        }
	nodeList.add(pparamNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new17() /* reduce AArrayParam */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParam pparamNode1;
        {
            // Block
        PTypeSpec ptypespecNode2;
        TId tidNode3;
        TLeftBracket tleftbracketNode4;
        TRightBracket trightbracketNode5;
        ptypespecNode2 = (PTypeSpec)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);
        tleftbracketNode4 = (TLeftBracket)nodeArrayList3.get(0);
        trightbracketNode5 = (TRightBracket)nodeArrayList4.get(0);

        pparamNode1 = new AArrayParam(ptypespecNode2, tidNode3, tleftbracketNode4, trightbracketNode5);
        }
	nodeList.add(pparamNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new18() /* reduce ACompoundStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PCompoundStmt pcompoundstmtNode1;
        {
            // Block
        TLeftBrace tleftbraceNode2;
        PLocalDecl plocaldeclNode3;
        PStmtList pstmtlistNode4;
        TRightBrace trightbraceNode5;
        tleftbraceNode2 = (TLeftBrace)nodeArrayList1.get(0);
        plocaldeclNode3 = (PLocalDecl)nodeArrayList2.get(0);
        pstmtlistNode4 = (PStmtList)nodeArrayList3.get(0);
        trightbraceNode5 = (TRightBrace)nodeArrayList4.get(0);

        pcompoundstmtNode1 = new ACompoundStmt(tleftbraceNode2, plocaldeclNode3, pstmtlistNode4, trightbraceNode5);
        }
	nodeList.add(pcompoundstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new19() /* reduce AStmtList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStmtList pstmtlistNode1;
        {
            // Block
        PStmtList pstmtlistNode2;
        PStmt pstmtNode3;
        pstmtlistNode2 = (PStmtList)nodeArrayList1.get(0);
        pstmtNode3 = (PStmt)nodeArrayList2.get(0);

        pstmtlistNode1 = new AStmtList(pstmtlistNode2, pstmtNode3);
        }
	nodeList.add(pstmtlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new20() /* reduce AEmptyStmtList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PStmtList pstmtlistNode1;
        {
            // Block

        pstmtlistNode1 = new AEmptyStmtList();
        }
	nodeList.add(pstmtlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new21() /* reduce AMatchedStmtStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStmt pstmtNode1;
        {
            // Block
        PMatchedStmt pmatchedstmtNode2;
        pmatchedstmtNode2 = (PMatchedStmt)nodeArrayList1.get(0);

        pstmtNode1 = new AMatchedStmtStmt(pmatchedstmtNode2);
        }
	nodeList.add(pstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new22() /* reduce AUnmatchedStmtStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStmt pstmtNode1;
        {
            // Block
        PUnmatchedStmt punmatchedstmtNode2;
        punmatchedstmtNode2 = (PUnmatchedStmt)nodeArrayList1.get(0);

        pstmtNode1 = new AUnmatchedStmtStmt(punmatchedstmtNode2);
        }
	nodeList.add(pstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new23() /* reduce AMatchedIfMatchedStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PMatchedStmt pmatchedstmtNode1;
        {
            // Block
        TIf tifNode2;
        TLeftParenthesis tleftparenthesisNode3;
        PExpression pexpressionNode4;
        TRightParenthesis trightparenthesisNode5;
        PMatchedStmt pmatchedstmtNode6;
        TElse telseNode7;
        PMatchedStmt pmatchedstmtNode8;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        tleftparenthesisNode3 = (TLeftParenthesis)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);
        trightparenthesisNode5 = (TRightParenthesis)nodeArrayList4.get(0);
        pmatchedstmtNode6 = (PMatchedStmt)nodeArrayList5.get(0);
        telseNode7 = (TElse)nodeArrayList6.get(0);
        pmatchedstmtNode8 = (PMatchedStmt)nodeArrayList7.get(0);

        pmatchedstmtNode1 = new AMatchedIfMatchedStmt(tifNode2, tleftparenthesisNode3, pexpressionNode4, trightparenthesisNode5, pmatchedstmtNode6, telseNode7, pmatchedstmtNode8);
        }
	nodeList.add(pmatchedstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new24() /* reduce AOtherStmtMatchedStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PMatchedStmt pmatchedstmtNode1;
        {
            // Block
        POtherStmt potherstmtNode2;
        potherstmtNode2 = (POtherStmt)nodeArrayList1.get(0);

        pmatchedstmtNode1 = new AOtherStmtMatchedStmt(potherstmtNode2);
        }
	nodeList.add(pmatchedstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new25() /* reduce AUnmatchedIfUnmatchedStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PUnmatchedStmt punmatchedstmtNode1;
        {
            // Block
        TIf tifNode2;
        TLeftParenthesis tleftparenthesisNode3;
        PExpression pexpressionNode4;
        TRightParenthesis trightparenthesisNode5;
        PStmt pstmtNode6;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        tleftparenthesisNode3 = (TLeftParenthesis)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);
        trightparenthesisNode5 = (TRightParenthesis)nodeArrayList4.get(0);
        pstmtNode6 = (PStmt)nodeArrayList5.get(0);

        punmatchedstmtNode1 = new AUnmatchedIfUnmatchedStmt(tifNode2, tleftparenthesisNode3, pexpressionNode4, trightparenthesisNode5, pstmtNode6);
        }
	nodeList.add(punmatchedstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new26() /* reduce AUnmatchedIfElseUnmatchedStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PUnmatchedStmt punmatchedstmtNode1;
        {
            // Block
        TIf tifNode2;
        TLeftParenthesis tleftparenthesisNode3;
        PExpression pexpressionNode4;
        TRightParenthesis trightparenthesisNode5;
        PMatchedStmt pmatchedstmtNode6;
        TElse telseNode7;
        PUnmatchedStmt punmatchedstmtNode8;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        tleftparenthesisNode3 = (TLeftParenthesis)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);
        trightparenthesisNode5 = (TRightParenthesis)nodeArrayList4.get(0);
        pmatchedstmtNode6 = (PMatchedStmt)nodeArrayList5.get(0);
        telseNode7 = (TElse)nodeArrayList6.get(0);
        punmatchedstmtNode8 = (PUnmatchedStmt)nodeArrayList7.get(0);

        punmatchedstmtNode1 = new AUnmatchedIfElseUnmatchedStmt(tifNode2, tleftparenthesisNode3, pexpressionNode4, trightparenthesisNode5, pmatchedstmtNode6, telseNode7, punmatchedstmtNode8);
        }
	nodeList.add(punmatchedstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new27() /* reduce AExpressionStmtOtherStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POtherStmt potherstmtNode1;
        {
            // Block
        PExpressionStmt pexpressionstmtNode2;
        pexpressionstmtNode2 = (PExpressionStmt)nodeArrayList1.get(0);

        potherstmtNode1 = new AExpressionStmtOtherStmt(pexpressionstmtNode2);
        }
	nodeList.add(potherstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new28() /* reduce ACompoundStmtOtherStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POtherStmt potherstmtNode1;
        {
            // Block
        PCompoundStmt pcompoundstmtNode2;
        pcompoundstmtNode2 = (PCompoundStmt)nodeArrayList1.get(0);

        potherstmtNode1 = new ACompoundStmtOtherStmt(pcompoundstmtNode2);
        }
	nodeList.add(potherstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new29() /* reduce AIterationStmtOtherStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POtherStmt potherstmtNode1;
        {
            // Block
        PIterationStmt piterationstmtNode2;
        piterationstmtNode2 = (PIterationStmt)nodeArrayList1.get(0);

        potherstmtNode1 = new AIterationStmtOtherStmt(piterationstmtNode2);
        }
	nodeList.add(potherstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new30() /* reduce AReturnStmtOtherStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POtherStmt potherstmtNode1;
        {
            // Block
        PReturnStmt preturnstmtNode2;
        preturnstmtNode2 = (PReturnStmt)nodeArrayList1.get(0);

        potherstmtNode1 = new AReturnStmtOtherStmt(preturnstmtNode2);
        }
	nodeList.add(potherstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new31() /* reduce AExpressionStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpressionStmt pexpressionstmtNode1;
        {
            // Block
        PExpression pexpressionNode2;
        TSemi tsemiNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tsemiNode3 = (TSemi)nodeArrayList2.get(0);

        pexpressionstmtNode1 = new AExpressionStmt(pexpressionNode2, tsemiNode3);
        }
	nodeList.add(pexpressionstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new32() /* reduce AEmptyExpressionStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpressionStmt pexpressionstmtNode1;
        {
            // Block
        TSemi tsemiNode2;
        tsemiNode2 = (TSemi)nodeArrayList1.get(0);

        pexpressionstmtNode1 = new AEmptyExpressionStmt(tsemiNode2);
        }
	nodeList.add(pexpressionstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new33() /* reduce AIterationStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIterationStmt piterationstmtNode1;
        {
            // Block
        TWhile twhileNode2;
        TLeftParenthesis tleftparenthesisNode3;
        PExpression pexpressionNode4;
        TRightParenthesis trightparenthesisNode5;
        POtherStmt potherstmtNode6;
        twhileNode2 = (TWhile)nodeArrayList1.get(0);
        tleftparenthesisNode3 = (TLeftParenthesis)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);
        trightparenthesisNode5 = (TRightParenthesis)nodeArrayList4.get(0);
        potherstmtNode6 = (POtherStmt)nodeArrayList5.get(0);

        piterationstmtNode1 = new AIterationStmt(twhileNode2, tleftparenthesisNode3, pexpressionNode4, trightparenthesisNode5, potherstmtNode6);
        }
	nodeList.add(piterationstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new34() /* reduce AVoidReturnStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PReturnStmt preturnstmtNode1;
        {
            // Block
        TReturn treturnNode2;
        TSemi tsemiNode3;
        treturnNode2 = (TReturn)nodeArrayList1.get(0);
        tsemiNode3 = (TSemi)nodeArrayList2.get(0);

        preturnstmtNode1 = new AVoidReturnStmt(treturnNode2, tsemiNode3);
        }
	nodeList.add(preturnstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new35() /* reduce AExpressionReturnStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PReturnStmt preturnstmtNode1;
        {
            // Block
        TReturn treturnNode2;
        PExpression pexpressionNode3;
        TSemi tsemiNode4;
        treturnNode2 = (TReturn)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList2.get(0);
        tsemiNode4 = (TSemi)nodeArrayList3.get(0);

        preturnstmtNode1 = new AExpressionReturnStmt(treturnNode2, pexpressionNode3, tsemiNode4);
        }
	nodeList.add(preturnstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new36() /* reduce ASimpleVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PVar pvarNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pvarNode1 = new ASimpleVar(tidNode2);
        }
	nodeList.add(pvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new37() /* reduce AArrayVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PVar pvarNode1;
        {
            // Block
        TId tidNode2;
        TLeftBracket tleftbracketNode3;
        PExpression pexpressionNode4;
        TRightBracket trightbracketNode5;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tleftbracketNode3 = (TLeftBracket)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);
        trightbracketNode5 = (TRightBracket)nodeArrayList4.get(0);

        pvarNode1 = new AArrayVar(tidNode2, tleftbracketNode3, pexpressionNode4, trightbracketNode5);
        }
	nodeList.add(pvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new38() /* reduce AAssignExpressionExpression */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        PVar pvarNode2;
        TAssign tassignNode3;
        PExpression pexpressionNode4;
        pvarNode2 = (PVar)nodeArrayList1.get(0);
        tassignNode3 = (TAssign)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AAssignExpressionExpression(pvarNode2, tassignNode3, pexpressionNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new39() /* reduce ASimpleExpressionExpression */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        PSimpleExpression psimpleexpressionNode2;
        psimpleexpressionNode2 = (PSimpleExpression)nodeArrayList1.get(0);

        pexpressionNode1 = new ASimpleExpressionExpression(psimpleexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new40() /* reduce ARelopExpressionSimpleExpression */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSimpleExpression psimpleexpressionNode1;
        {
            // Block
        PAdditiveExpression padditiveexpressionNode2;
        PRelop prelopNode3;
        PAdditiveExpression padditiveexpressionNode4;
        padditiveexpressionNode2 = (PAdditiveExpression)nodeArrayList1.get(0);
        prelopNode3 = (PRelop)nodeArrayList2.get(0);
        padditiveexpressionNode4 = (PAdditiveExpression)nodeArrayList3.get(0);

        psimpleexpressionNode1 = new ARelopExpressionSimpleExpression(padditiveexpressionNode2, prelopNode3, padditiveexpressionNode4);
        }
	nodeList.add(psimpleexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new41() /* reduce AAdditiveExpressionSimpleExpression */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSimpleExpression psimpleexpressionNode1;
        {
            // Block
        PAdditiveExpression padditiveexpressionNode2;
        padditiveexpressionNode2 = (PAdditiveExpression)nodeArrayList1.get(0);

        psimpleexpressionNode1 = new AAdditiveExpressionSimpleExpression(padditiveexpressionNode2);
        }
	nodeList.add(psimpleexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new42() /* reduce ALessThanOrEqRelop */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PRelop prelopNode1;
        {
            // Block
        TLessThanOrEq tlessthanoreqNode2;
        tlessthanoreqNode2 = (TLessThanOrEq)nodeArrayList1.get(0);

        prelopNode1 = new ALessThanOrEqRelop(tlessthanoreqNode2);
        }
	nodeList.add(prelopNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new43() /* reduce ALessThanRelop */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PRelop prelopNode1;
        {
            // Block
        TLessThan tlessthanNode2;
        tlessthanNode2 = (TLessThan)nodeArrayList1.get(0);

        prelopNode1 = new ALessThanRelop(tlessthanNode2);
        }
	nodeList.add(prelopNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new44() /* reduce AGreaterThanRelop */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PRelop prelopNode1;
        {
            // Block
        TGreaterThan tgreaterthanNode2;
        tgreaterthanNode2 = (TGreaterThan)nodeArrayList1.get(0);

        prelopNode1 = new AGreaterThanRelop(tgreaterthanNode2);
        }
	nodeList.add(prelopNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new45() /* reduce AGreaterThanOrEqRelop */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PRelop prelopNode1;
        {
            // Block
        TGreaterThanOrEq tgreaterthanoreqNode2;
        tgreaterthanoreqNode2 = (TGreaterThanOrEq)nodeArrayList1.get(0);

        prelopNode1 = new AGreaterThanOrEqRelop(tgreaterthanoreqNode2);
        }
	nodeList.add(prelopNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new46() /* reduce AEqualsRelop */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PRelop prelopNode1;
        {
            // Block
        TEquals tequalsNode2;
        tequalsNode2 = (TEquals)nodeArrayList1.get(0);

        prelopNode1 = new AEqualsRelop(tequalsNode2);
        }
	nodeList.add(prelopNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new47() /* reduce ANotEqualsRelop */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PRelop prelopNode1;
        {
            // Block
        TNotEquals tnotequalsNode2;
        tnotequalsNode2 = (TNotEquals)nodeArrayList1.get(0);

        prelopNode1 = new ANotEqualsRelop(tnotequalsNode2);
        }
	nodeList.add(prelopNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new48() /* reduce AAdditiveExpressionAdditiveExpression */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAdditiveExpression padditiveexpressionNode1;
        {
            // Block
        PAdditiveExpression padditiveexpressionNode2;
        PAddop paddopNode3;
        PTerm ptermNode4;
        padditiveexpressionNode2 = (PAdditiveExpression)nodeArrayList1.get(0);
        paddopNode3 = (PAddop)nodeArrayList2.get(0);
        ptermNode4 = (PTerm)nodeArrayList3.get(0);

        padditiveexpressionNode1 = new AAdditiveExpressionAdditiveExpression(padditiveexpressionNode2, paddopNode3, ptermNode4);
        }
	nodeList.add(padditiveexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new49() /* reduce ATermAdditiveExpression */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAdditiveExpression padditiveexpressionNode1;
        {
            // Block
        PTerm ptermNode2;
        ptermNode2 = (PTerm)nodeArrayList1.get(0);

        padditiveexpressionNode1 = new ATermAdditiveExpression(ptermNode2);
        }
	nodeList.add(padditiveexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new50() /* reduce APlusAddop */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAddop paddopNode1;
        {
            // Block
        TPlus tplusNode2;
        tplusNode2 = (TPlus)nodeArrayList1.get(0);

        paddopNode1 = new APlusAddop(tplusNode2);
        }
	nodeList.add(paddopNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new51() /* reduce AMinusAddop */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAddop paddopNode1;
        {
            // Block
        TMinus tminusNode2;
        tminusNode2 = (TMinus)nodeArrayList1.get(0);

        paddopNode1 = new AMinusAddop(tminusNode2);
        }
	nodeList.add(paddopNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new52() /* reduce ATermTerm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        PTerm ptermNode2;
        PMulop pmulopNode3;
        PFactor pfactorNode4;
        ptermNode2 = (PTerm)nodeArrayList1.get(0);
        pmulopNode3 = (PMulop)nodeArrayList2.get(0);
        pfactorNode4 = (PFactor)nodeArrayList3.get(0);

        ptermNode1 = new ATermTerm(ptermNode2, pmulopNode3, pfactorNode4);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new53() /* reduce AFactorTerm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        PFactor pfactorNode2;
        pfactorNode2 = (PFactor)nodeArrayList1.get(0);

        ptermNode1 = new AFactorTerm(pfactorNode2);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new54() /* reduce AMultiplicationMulop */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PMulop pmulopNode1;
        {
            // Block
        TMultiplication tmultiplicationNode2;
        tmultiplicationNode2 = (TMultiplication)nodeArrayList1.get(0);

        pmulopNode1 = new AMultiplicationMulop(tmultiplicationNode2);
        }
	nodeList.add(pmulopNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new55() /* reduce ADivisionMulop */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PMulop pmulopNode1;
        {
            // Block
        TDivision tdivisionNode2;
        tdivisionNode2 = (TDivision)nodeArrayList1.get(0);

        pmulopNode1 = new ADivisionMulop(tdivisionNode2);
        }
	nodeList.add(pmulopNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new56() /* reduce AFactorFactor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        TLeftParenthesis tleftparenthesisNode2;
        PExpression pexpressionNode3;
        TRightParenthesis trightparenthesisNode4;
        tleftparenthesisNode2 = (TLeftParenthesis)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList2.get(0);
        trightparenthesisNode4 = (TRightParenthesis)nodeArrayList3.get(0);

        pfactorNode1 = new AFactorFactor(tleftparenthesisNode2, pexpressionNode3, trightparenthesisNode4);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new57() /* reduce AVarFactor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        PVar pvarNode2;
        pvarNode2 = (PVar)nodeArrayList1.get(0);

        pfactorNode1 = new AVarFactor(pvarNode2);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new58() /* reduce ANumFactor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        TNum tnumNode2;
        tnumNode2 = (TNum)nodeArrayList1.get(0);

        pfactorNode1 = new ANumFactor(tnumNode2);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new59() /* reduce AStringFactor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        TStringLiteral tstringliteralNode2;
        tstringliteralNode2 = (TStringLiteral)nodeArrayList1.get(0);

        pfactorNode1 = new AStringFactor(tstringliteralNode2);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new60() /* reduce ACallFactor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        PCall pcallNode2;
        pcallNode2 = (PCall)nodeArrayList1.get(0);

        pfactorNode1 = new ACallFactor(pcallNode2);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new61() /* reduce ACall */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PCall pcallNode1;
        {
            // Block
        TId tidNode2;
        TLeftParenthesis tleftparenthesisNode3;
        PArgList parglistNode4;
        TRightParenthesis trightparenthesisNode5;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tleftparenthesisNode3 = (TLeftParenthesis)nodeArrayList2.get(0);
        parglistNode4 = (PArgList)nodeArrayList3.get(0);
        trightparenthesisNode5 = (TRightParenthesis)nodeArrayList4.get(0);

        pcallNode1 = new ACall(tidNode2, tleftparenthesisNode3, parglistNode4, trightparenthesisNode5);
        }
	nodeList.add(pcallNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new62() /* reduce ASequenceArgList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PArgList parglistNode1;
        {
            // Block
        PArgList parglistNode2;
        TComma tcommaNode3;
        PExpression pexpressionNode4;
        parglistNode2 = (PArgList)nodeArrayList1.get(0);
        tcommaNode3 = (TComma)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);

        parglistNode1 = new ASequenceArgList(parglistNode2, tcommaNode3, pexpressionNode4);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new63() /* reduce ASingleArgList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PArgList parglistNode1;
        {
            // Block
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);

        parglistNode1 = new ASingleArgList(pexpressionNode2);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new64() /* reduce AEmptyArgList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PArgList parglistNode1;
        {
            // Block

        parglistNode1 = new AEmptyArgList();
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new65() /* reduce ATerminal$Decl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PDecl pdeclNode1;
        pdeclNode1 = (PDecl)nodeArrayList1.get(0);
	if(pdeclNode1 != null)
	{
	  listNode2.add(pdeclNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new66() /* reduce ANonTerminal$Decl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PDecl pdeclNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pdeclNode2 = (PDecl)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pdeclNode2 != null)
	{
	  listNode3.add(pdeclNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new67() /* reduce ATerminal$ParamList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PParamList pparamlistNode1;
        pparamlistNode1 = (PParamList)nodeArrayList1.get(0);
	if(pparamlistNode1 != null)
	{
	  listNode2.add(pparamlistNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new68() /* reduce ANonTerminal$ParamList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PParamList pparamlistNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pparamlistNode2 = (PParamList)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pparamlistNode2 != null)
	{
	  listNode3.add(pparamlistNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {0, SHIFT, 1}, {1, SHIFT, 2}, {2, SHIFT, 3}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 3}, {8, SHIFT, 11}, },
			{{-1, ERROR, 4}, {33, ACCEPT, -1}, },
			{{-1, REDUCE, 0}, },
			{{-1, REDUCE, 65}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 3}, },
			{{-1, ERROR, 9}, {8, SHIFT, 12}, },
			{{-1, REDUCE, 1}, {0, SHIFT, 1}, {1, SHIFT, 2}, {2, SHIFT, 3}, },
			{{-1, ERROR, 11}, {23, SHIFT, 14}, },
			{{-1, ERROR, 12}, {21, SHIFT, 15}, {23, SHIFT, 16}, {25, SHIFT, 17}, },
			{{-1, REDUCE, 66}, },
			{{-1, ERROR, 14}, {0, SHIFT, 1}, {1, SHIFT, 2}, {2, SHIFT, 18}, },
			{{-1, REDUCE, 4}, },
			{{-1, ERROR, 16}, {0, SHIFT, 1}, {1, SHIFT, 2}, {2, SHIFT, 18}, },
			{{-1, ERROR, 17}, {7, SHIFT, 25}, },
			{{-1, REDUCE, 13}, },
			{{-1, ERROR, 19}, {8, SHIFT, 26}, },
			{{-1, ERROR, 20}, {24, SHIFT, 27}, },
			{{-1, REDUCE, 67}, {22, SHIFT, 28}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 12}, {0, SHIFT, 1}, {1, SHIFT, 2}, },
			{{-1, ERROR, 24}, {24, SHIFT, 30}, },
			{{-1, ERROR, 25}, {26, SHIFT, 31}, },
			{{-1, REDUCE, 16}, {25, SHIFT, 32}, },
			{{-1, ERROR, 27}, {27, SHIFT, 33}, },
			{{-1, ERROR, 28}, {0, SHIFT, 1}, {1, SHIFT, 2}, },
			{{-1, REDUCE, 68}, {22, SHIFT, 28}, },
			{{-1, ERROR, 30}, {27, SHIFT, 33}, },
			{{-1, ERROR, 31}, {21, SHIFT, 37}, },
			{{-1, ERROR, 32}, {26, SHIFT, 38}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 20}, {0, SHIFT, 1}, {1, SHIFT, 2}, },
			{{-1, REDUCE, 8}, },
			{{-1, ERROR, 41}, {8, SHIFT, 43}, },
			{{-1, ERROR, 42}, {3, SHIFT, 44}, {5, SHIFT, 45}, {6, SHIFT, 46}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {21, SHIFT, 50}, {23, SHIFT, 51}, {27, SHIFT, 33}, {28, SHIFT, 52}, },
			{{-1, ERROR, 43}, {21, SHIFT, 15}, {25, SHIFT, 17}, },
			{{-1, ERROR, 44}, {23, SHIFT, 68}, },
			{{-1, ERROR, 45}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {21, SHIFT, 69}, {23, SHIFT, 51}, },
			{{-1, ERROR, 46}, {23, SHIFT, 71}, },
			{{-1, REDUCE, 58}, },
			{{-1, REDUCE, 36}, {23, SHIFT, 72}, {25, SHIFT, 73}, },
			{{-1, REDUCE, 59}, },
			{{-1, REDUCE, 32}, },
			{{-1, ERROR, 51}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {23, SHIFT, 51}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 28}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 27}, },
			{{-1, REDUCE, 29}, },
			{{-1, REDUCE, 30}, },
			{{-1, REDUCE, 57}, {20, SHIFT, 75}, },
			{{-1, ERROR, 62}, {21, SHIFT, 76}, },
			{{-1, REDUCE, 39}, },
			{{-1, REDUCE, 41}, {10, SHIFT, 77}, {11, SHIFT, 78}, {14, SHIFT, 79}, {15, SHIFT, 80}, {16, SHIFT, 81}, {17, SHIFT, 82}, {18, SHIFT, 83}, {19, SHIFT, 84}, },
			{{-1, REDUCE, 49}, {12, SHIFT, 87}, {13, SHIFT, 88}, },
			{{-1, REDUCE, 53}, },
			{{-1, REDUCE, 60}, },
			{{-1, ERROR, 68}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {23, SHIFT, 51}, },
			{{-1, REDUCE, 34}, },
			{{-1, ERROR, 70}, {21, SHIFT, 91}, },
			{{-1, ERROR, 71}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {23, SHIFT, 51}, },
			{{-1, REDUCE, 64}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {23, SHIFT, 51}, },
			{{-1, ERROR, 73}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {23, SHIFT, 51}, },
			{{-1, ERROR, 74}, {24, SHIFT, 96}, },
			{{-1, ERROR, 75}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {23, SHIFT, 51}, },
			{{-1, REDUCE, 31}, },
			{{-1, REDUCE, 50}, },
			{{-1, REDUCE, 51}, },
			{{-1, REDUCE, 43}, },
			{{-1, REDUCE, 42}, },
			{{-1, REDUCE, 44}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 47}, },
			{{-1, ERROR, 85}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {23, SHIFT, 51}, },
			{{-1, ERROR, 86}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {23, SHIFT, 51}, },
			{{-1, REDUCE, 55}, },
			{{-1, REDUCE, 54}, },
			{{-1, ERROR, 89}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {23, SHIFT, 51}, },
			{{-1, ERROR, 90}, {24, SHIFT, 102}, },
			{{-1, REDUCE, 35}, },
			{{-1, ERROR, 92}, {24, SHIFT, 103}, },
			{{-1, REDUCE, 63}, },
			{{-1, ERROR, 94}, {22, SHIFT, 104}, {24, SHIFT, 105}, },
			{{-1, ERROR, 95}, {26, SHIFT, 106}, },
			{{-1, REDUCE, 56}, },
			{{-1, REDUCE, 38}, },
			{{-1, REDUCE, 57}, },
			{{-1, REDUCE, 40}, {10, SHIFT, 77}, {11, SHIFT, 78}, },
			{{-1, REDUCE, 48}, {12, SHIFT, 87}, {13, SHIFT, 88}, },
			{{-1, REDUCE, 52}, },
			{{-1, ERROR, 102}, {3, SHIFT, 44}, {5, SHIFT, 45}, {6, SHIFT, 46}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {21, SHIFT, 50}, {23, SHIFT, 51}, {27, SHIFT, 33}, },
			{{-1, ERROR, 103}, {5, SHIFT, 45}, {6, SHIFT, 46}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {21, SHIFT, 50}, {23, SHIFT, 51}, {27, SHIFT, 33}, },
			{{-1, ERROR, 104}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {23, SHIFT, 51}, },
			{{-1, REDUCE, 61}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 21}, {4, SHIFT, 111}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 62}, },
			{{-1, ERROR, 111}, {3, SHIFT, 44}, {5, SHIFT, 45}, {6, SHIFT, 46}, {7, SHIFT, 47}, {8, SHIFT, 48}, {9, SHIFT, 49}, {21, SHIFT, 50}, {23, SHIFT, 51}, {27, SHIFT, 33}, },
			{{-1, REDUCE, 23}, },
			{{-1, REDUCE, 26}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 4}, },
			{{-1, 5}, },
			{{-1, 6}, {10, 13}, },
			{{-1, 7}, {39, 40}, },
			{{-1, 8}, },
			{{-1, 39}, },
			{{-1, 19}, {0, 9}, {10, 9}, {39, 41}, },
			{{-1, 20}, {16, 24}, },
			{{-1, 21}, {23, 29}, },
			{{-1, 22}, {28, 35}, },
			{{-1, 53}, {27, 34}, {30, 36}, },
			{{-1, 42}, },
			{{-1, 54}, {102, 107}, },
			{{-1, 55}, {102, 108}, {111, 112}, },
			{{-1, 56}, {111, 113}, },
			{{-1, 57}, {103, 109}, },
			{{-1, 58}, },
			{{-1, 59}, },
			{{-1, 60}, },
			{{-1, 61}, {85, 98}, {86, 98}, {89, 98}, },
			{{-1, 62}, {45, 70}, {51, 74}, {68, 90}, {71, 92}, {72, 93}, {73, 95}, {75, 97}, {104, 110}, },
			{{-1, 63}, },
			{{-1, 85}, },
			{{-1, 64}, {85, 99}, },
			{{-1, 86}, },
			{{-1, 65}, {86, 100}, },
			{{-1, 89}, },
			{{-1, 66}, {89, 101}, },
			{{-1, 67}, },
			{{-1, 94}, },
			{{-1, 10}, },
			{{-1, 23}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: int, string, void",
			"expecting: id",
			"expecting: EOF",
			"expecting: int, string, void, EOF",
			"expecting: '('",
			"expecting: semi, '(', '['",
			"expecting: int, string, void, if, return, while, num, id, string literal, semi, '(', '{', '}', EOF",
			"expecting: num",
			"expecting: ')'",
			"expecting: int, string, ',', ')'",
			"expecting: int, string, ')'",
			"expecting: ']'",
			"expecting: int, string, ',', ')', '['",
			"expecting: '{'",
			"expecting: int, string",
			"expecting: semi",
			"expecting: int, string, if, return, while, num, id, string literal, semi, '(', '{', '}'",
			"expecting: if, return, while, num, id, string literal, semi, '(', '{', '}'",
			"expecting: semi, '['",
			"expecting: num, id, string literal, semi, '('",
			"expecting: '+', '-', '/', '*', '<', '<=', '>', '>=', '==', '!=', semi, ',', ')', ']'",
			"expecting: '+', '-', '/', '*', '<', '<=', '>', '>=', '==', '!=', '=', semi, ',', '(', ')', '[', ']'",
			"expecting: if, else, return, while, num, id, string literal, semi, '(', '{', '}'",
			"expecting: num, id, string literal, '('",
			"expecting: int, string, void, if, else, return, while, num, id, string literal, semi, '(', '{', '}', EOF",
			"expecting: '+', '-', '/', '*', '<', '<=', '>', '>=', '==', '!=', '=', semi, ',', ')', ']'",
			"expecting: semi, ',', ')', ']'",
			"expecting: '+', '-', '<', '<=', '>', '>=', '==', '!=', semi, ',', ')', ']'",
			"expecting: num, id, string literal, ',', '(', ')'",
			"expecting: ',', ')'",
			"expecting: '+', '-', semi, ',', ')', ']'",
			"expecting: if, return, while, num, id, string literal, semi, '(', '{'",
			"expecting: return, while, num, id, string literal, semi, '(', '{'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 1, 1, 2, 2, 3, 3, 3, 1, 3, 4, 5, 3, 0, 6, 0, 7, 8, 1, 8, 9, 9, 10, 8, 11, 12, 13, 14, 9, 13, 15, 11, 16, 3, 9, 3, 6, 9, 16, 16, 1, 17, 18, 4, 19, 4, 20, 21, 20, 22, 23, 24, 22, 17, 17, 17, 22, 22, 22, 22, 25, 15, 26, 27, 20, 20, 20, 23, 22, 15, 23, 28, 23, 8, 23, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 8, 22, 8, 29, 29, 11, 20, 26, 20, 30, 20, 20, 31, 32, 23, 20, 25, 17, 22, 22, 29, 31, 22, 17, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
